---
:api_key: 45e53faffe2b4b9091b2c0d67f13cd9f
:password: f438ec4d7b14c4cc81ff4a38862749ee
:theme_id: '73'
:preview_url: https://www.ludikmoda.com.br/loja/loja.php?loja=901550&opencode_theme=612ffb7e4eb91
